version: 2.1
orbs:
  python: circleci/python@1.4.0
  jira: circleci/jira@1.0.5

jobs:
  build:
    executor: python/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run
      - run:
          name: Deploy binary to S3
          command: |
            python3 -m pip install awscli
            pip install awscli --force-reinstall --upgrade
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_REGION
            aws s3 cp .pio/build/esp32dev/firmware.bin s3://mybucketplatformio/firmware.bin
workflows:
  main:
    jobs:
      - build
