version: 2.1
orbs:
  python: circleci/python@1.4.0
  jira: circleci/jira@1.0.5

jobs:
  build:
    executor: python/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run
      - run:
          name: Creating Dummy Artifacts
          command: |
            cd .pio/build/esp32dev
            echo "firmare.bin" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  main:
    jobs:
      - build
