version: 2.1
orbs:
  python: circleci/python@1.4.0
  jira: circleci/jira@1.0.5

jobs:
  build:
    executor: python/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run
      - run:
          name: Deploy binary to S3
          command: |
            pip install awscli --force-reinstall --upgrade
            aws configure set default.region eu-central-1

workflows:
  main:
    jobs:
      - build
