version: 2.1
orbs:
  python: circleci/python@1.4.0
  jira: circleci/jira@1.0.5

jobs:
  build:
    executor: python/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run
      - run:
          name: Build and run tests
          command: |
            platformio test -e esp32dev

      - run:
          name: Deploy binary to S3
          command: |
            sudo apt-get install -y awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_REGION
            aws s3 cp .pioenvs/esp32/firmware.bin s3://my-bucket/firmware.bin
workflows:
  main:
    jobs:
      - build
