/*******************************************************************************
 * Title                 :   Main
 * Filename              :   main.cpp
 * Author                :   Simone Gasparella
 * Origin Date           :   19/01/2022
 * Compiler              :   xtensa32 2.50200.97
 * Target                :   ESP32WROOMSE
 * Notes                 :   None
 *
 * THIS SOFTWARE IS PROVIDED BY SYSTEL ELETTRONICA "AS IS" AND ANY EXPRESSED
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL SYSTEL ELETTRONICA OR ITS CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 *
 *******************************************************************************/
/****************************************************************************
 * Doxygen C Template
 * Copyright (c) 2021 - Systel Elettronica - All Rights Reserved
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Template.
 *
 *****************************************************************************/
/*************** SOURCE REVISION LOG *****************************************
 *
 *    Date    Version   Author         Description
 *  19/01/22   1.0.0   Simone Gasparella   Initial Release.
 *
 *******************************************************************************/
/** @file : main.cpp
 *  @brief This is the main file of the project
 */

#include "main.h"
#include <machine.h>

/**
 * @brief  Function to execute the setup generated by the arduino framework
 * @param  None
 * @retval None
 */
void setup(void)
{
  /*start serial communication for debug purpose*/
  Serial.begin(115200);

  /*creation of the queues for exchange data*/
  Create_queue_for_exchange_alarms_between_uart_and_wifi();
  Create_queue_for_exchange_log_between_uart_and_wifi();
  Create_queue_for_exchange_state_between_uart_and_wifi();
  Create_queue_for_exchange_physics_between_uart_and_wifi();
  Create_queue_for_exchange_reports_between_uart_and_wifi();
  Create_queue_for_exchange_commands_status_between_uart_and_wifi();

  Create_queue_for_exchange_commands_between_wifi_and_uart();
  Create_queue_for_exchange_config_between_wifi_and_uart();
  Create_queue_for_exchange_program_upload_between_wifi_and_uart();

  /*tasks creation*/
  First_task_creation();
  Second_task_creation();
  Fourth_task_creation();
  Seventh_task_creation();
  Eight_task_creation();
}
/**
 * @brief  Function to execute in loop generated by the arduino framework
 * @param  None
 * @retval None
 */
void loop(void)
{
  machine_loop();
}